ARG REPOSITORY
ARG DUCKDB_VERSION

FROM ${REPOSITORY}:${DUCKDB_VERSION} AS libduckdb

FROM ruby:3-slim
ARG DUCKDB_VERSION
RUN apt-get update \
    && apt-get install -y --no-install-recommends make g++ \
    && rm -rf /var/lib/apt/lists/*
COPY --from=libduckdb /libduckdb /
RUN gem install duckdb -v "<=${DUCKDB_VERSION}"
COPY tests/test.rb /test.rb
