name: Build, test and release

on:
  push:
    branches:
      - "main"
  workflow_dispatch:
    inputs:
      scratch:
        description: 'Build scratch image'
        required: false
        type: boolean
      alpine:
        description: 'Build Alpine image'
        required: false
        type: boolean

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      alpine: ${{ steps.filter.outputs.alpine || inputs.alpine }}
      scratch: ${{ steps.filter.outputs.scratch  || inputs.scratch }}
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
        if: ${{ !inputs.scratch && !inputs.alpine }}
      -
        uses: dorny/paths-filter@v2
        id: filter
        if: ${{ !inputs.scratch && !inputs.alpine }}
        with:
          filters: |
            alpine:
              - '.github/workflows/main.yml'
              - 'tests/**'
              - 'Dockerfile.alpine'
            scratch:
              - '.github/workflows/main.yml'
              - 'tests/**'
              - 'Dockerfile.scratch'

  build-and-test-scratch:
    needs: changes
    if: ${{ needs.changes.outputs.scratch == 'true' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        duckdb_version: ['0.10.2', '0.9.2']
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-v2-scratch-${{ matrix.duckdb_version }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-v2-scratch-${{ matrix.duckdb_version }}-
      -
        name: Build and export to Docker
        uses: docker/build-push-action@v4
        with:
          build-args:
            DUCKDB_VERSION=${{ matrix.duckdb_version }}
          context: .
          file: ./Dockerfile.scratch
          load: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/libduckdb:${{ matrix.duckdb_version }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max
      -
        name: Test
        run: |
          docker build \
            --build-arg REPOSITORY="${{ secrets.DOCKERHUB_USERNAME }}/libduckdb" \
            --build-arg DUCKDB_VERSION="${{ matrix.duckdb_version }}" \
            -t test \
            -f tests/Dockerfile.slim \
            .
          docker run --rm test ruby test.rb
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          build-args:
            DUCKDB_VERSION=${{ matrix.duckdb_version }}
          context: .
          file: ./Dockerfile.scratch
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/libduckdb:${{ matrix.duckdb_version }}
      -
        # Temp fix
        # https://github.com/docker/build-push-action/issues/252
        # https://github.com/moby/buildkit/issues/1896
        name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

  build-and-test-alpine:
    needs: changes
    if: ${{ needs.changes.outputs.alpine == 'true' }}
    strategy:
      matrix:
        duckdb_version: ['0.10.2', '0.9.2']
        alpine_version: ['3.18', '3.19']
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-v2-alpine-${{ matrix.alpine_version }}-${{ matrix.duckdb_version }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-v2-alpine-${{ matrix.alpine_version }}-${{ matrix.duckdb_version }}-
      -
        name: Build and export to Docker
        uses: docker/build-push-action@v4
        with:
          build-args: |
            ALPINE_VERSION=${{ matrix.alpine_version }}
            DUCKDB_VERSION=${{ matrix.duckdb_version }}
          context: .
          file: ./Dockerfile.alpine
          load: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/libduckdb:${{ matrix.duckdb_version }}-alpine${{ matrix.alpine_version }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max
      -
        name: Test
        run: |
          docker build \
            --build-arg REPOSITORY="${{ secrets.DOCKERHUB_USERNAME }}/libduckdb" \
            --build-arg ALPINE_VERSION="${{ matrix.alpine_version }}" \
            --build-arg DUCKDB_VERSION="${{ matrix.duckdb_version }}" \
            -t test \
            -f tests/Dockerfile.alpine \
            .
          docker run --rm test ruby test.rb
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          build-args: |
            ALPINE_VERSION=${{ matrix.alpine_version }}
            DUCKDB_VERSION=${{ matrix.duckdb_version }}
          context: .
          file: ./Dockerfile.alpine
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/libduckdb:${{ matrix.duckdb_version }}-alpine${{ matrix.alpine_version }}
      -
        # Temp fix
        # https://github.com/docker/build-push-action/issues/252
        # https://github.com/moby/buildkit/issues/1896
        name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
